// <auto-generated />
using MasterMind.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MasterMind.Migrations
{
    [DbContext(typeof(ColorSelectionDBContext))]
    partial class ColorSelectionDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MasterMind.Models.ColorSelection", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CorrectColorCorrectPosition")
                        .HasColumnType("int");

                    b.Property<int>("CorrectColorWrongPosition")
                        .HasColumnType("int");

                    b.Property<string>("PlayerColor1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerColor2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerColor3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerColor4")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerId");

                    b.ToTable("ColorSelections");
                });

            modelBuilder.Entity("MasterMind.Models.GameColors", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("GameColor1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameColor2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameColor3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameColor4")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.ToTable("GameColors");
                });
#pragma warning restore 612, 618
        }
    }
}
